### ISSUE TITLE
API to allow the UA to adapt ptime dynamically

### ISSUE THREAD

**Issue by henbos** [henbos/webrtc-extensions#3]
This was discussed over at webrtc-pc here:
- Issue: https://github.com/w3c/webrtc-pc/issues/2300
- PR: https://github.com/w3c/webrtc-pc/pull/2309

Let's merge an equivalent of that PR in this extension spec. See review status there. Address nits and merge here.

**Comment by henbos** [comment]
I filed this for you @eladalon1983

**Comment by eladalon1983** [comment]
Thanks!
