### ISSUE TITLE
Clarify how playoutDelayHint works in the case of A/V sync

### ISSUE THREAD

**Issue by henbos** [henbos/webrtc-extensions#5]
If multiple tracks are meant to be synchronized due to having the same stream label we'll have multiple remote tracks, i.e. multiple receivers, which potentially could mean we have multiple contradictory playoutDelayHint hints.

Can we clarify, i.e. "use the largest hint for all" or "use the smallest hint for all" etc.

Assigned to @kuddai

**Comment by henbos** [comment]
For reference, lip sync is defined here:
https://tools.ietf.org/html/rfc5888#section-7

These should be the same as the receiver.[[AssociatedRemoteMediaStreams]] in webrtc-pc:
https://w3c.github.io/webrtc-pc/#dfn-associatedremotemediastreams

I believe you have a proposal for this issue.

**Comment by fippo** [comment]
this looks like it can be closed? :+1: for documenting it

**Comment by henbos** [comment]
Yes, thanks!
